apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site-ingress
  namespace: static-site-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: myWebsit       # استبدل host باسما أو استخدم ملف hosts محلياً
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-site-svc
            port:
              number: 80

