apiVersion: v1
kind: Service
metadata:
  name: static-site-svc
  namespace: static-site-demo
spec:
  selector:
    app: static-site
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP

