apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-site
  namespace: argocd          # عادة Argo CD مثبت في namespace argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<username>/static-site-demo.git'
    targetRevision: HEAD
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: static-site-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

